### ISSUE TITLE
Prometheus 2.7.x fork

### ISSUE THREAD

**Issue by matejzero** [free/prometheus#7]
Hello,

is it possible to get a new release for 2.7.0?

I also saw they are planing on releasing Prometheus 3.0 in the near feature. This could be the time to try and push for xrate in master Prometheus, since it's a major release.

**Comment by free** [comment]
I usually only cut a release whenever there's a full release of Prometheus, not for every release candidate. The reason is that it takes a while to merge, resolve the conflicts and then probably half an hour to an hour of  my laptop being dead slow while it builds the binaries for all platforms.

I can try to do the merge and resolve the conflicts when I find some time, as there will likely be some conflicts due to the subquery support that has been added. But you'll have to build your own binary. You just need to run `promu build` (or `promu crossbuild`, if you need binaries for other platforms, for some reason).

I'll let you know if and when I've done the merge.

**Comment by matejzero** [comment]
O I’m sorry, I dont know why I thought 2.7.0 was a full release!

On that case dont bother, I’ll wait until full release.

Thanks

On 18 Jan 2019, at 21:50, Alin Sinpalean <notifications@github.com> wrote:

I usually only cut a release whenever there's a full release of Prometheus,
not for every release candidate. The reason is that it takes a while to
merge, resolve the conflicts and then probably half an hour to an hour of
my laptop being dead slow while it builds the binaries for all platforms.

I can try to do the merge and resolve the conflicts when I find some time,
as there will likely be some conflicts due to the subquery support that has
been added. But you'll have to build your own binary. You just need to
run promu
build (or promu crossbuild, if you need binaries for other platforms, for
some reason).

I'll let you know if and when I've done the merge.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/free/prometheus/issues/7#issuecomment-455683371>, or mute
the thread
